name: Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}
      - name: Run Tests
        run: vendor/bin/phpunit --no-coverage
